### PR TITLE
Updated init, horizon and test so that it will import using only import Aerolyzer

### PR DESCRIPTION
**Pull request by wingarlo**
Reverts Aerolyzer/Aerolyzer#90

### CODE REVIEW

**Comment by kwhitehall** [comment]
Hey @wingarlo this PR says that the PR that your test file is being reverted, but it is actually adding 3 files to the codebase. Can you please explain? Also why the merger before?

**Comment by wingarlo** [comment]
@kwhitehall I meant to create another pull request where I removed my test file and added my changes to __init__.py and horizon.py, though I accidentally merged the pull request, so I reverted it.

**Comment by kwhitehall** [comment]
Ok @wingarlo. I see the convo @ issue #94, so now I follow. 
Couple things here. 
1. This PR and commit log should be worded such that it reflects the functionality being added to the codebase. 'Revert Adding test file' is very vague (and somewhat misleading as more than one file is being added) so please provide more details on what the edits of these files are actually for. 
2. @lamki866 @wingarlo @RossDan96 please do not revert anything on this codebase without consultation with myself. As this is the core project's codebase, we'll like to keep the log as clean as possible.

**Comment by wingarlo** [comment]
I do not want to revert. I accidentally merged, though still want the files on Aerolyzer. Revert should not go through.

**Pull request closed without merging**
