### PR TITLE
Tensorflow Test folder

### PR DESCRIPTION
**Pull request by RossDan96**

### CODE REVIEW

**Comment by kwhitehall** [comment]
Thanks @RossDan96. Currently reviewing.

**Comment by kwhitehall** [comment]
Hi @RossDan96 what are all of these doc files? 
And what are all of these python files? Are you trying to add the tensorflow source code to the codebase?

**Comment by RossDan96** [comment]
The third Pull from the Desktop branch is just my Technology Review doc. 

The tensorflow test folder currently contains the entire Docker container that we were using for testing. The Python code is dictating how tensorflow receives images to retrain the classifier and how, given an image, tensorflow returns it’s classification results. 
I’m not trying to add tensorflow to our codebase, I was just trying to see how a Docker container might call on tensorflow for its dependencies.
If you don’t want this whole Docker container just sitting in a subfolder in this repository, I’d understand. It was just an experiment we were trying in order to see how effective supervised classification might be. The original repository is https://github.com/llSourcell/tensorflow_image_classifier?files=1

Hope that answers your questions

**Comment by kwhitehall** [comment]
Thanks for the response @RossDan96 
1. The technical review docs, please remove from this PR and submit in a separate one.
2. As for the Docker container experiment, please test it out locally on your fork. Feel free to demo in the next meeting. Depending on those results, we can then update this codebase accordingly.

**Pull request closed without merging**
