### PR TITLE
Updated README and added license copy pdf

### PR DESCRIPTION
**Pull request by jessehanson**
Added Apache License v2.0 in a pdf file and updated the README accordingly.

### CODE REVIEW

**Comment by kwhitehall** [comment]
Nice @jessehanson. Can you please make the license file a text file? The reason for this change is a txt file doesn't require a third party reader, and as this is a license, with limited formatting, etc. the min requirement on the user's end would be preferred.

**Comment by kwhitehall** [comment]
Hey @jessehanson, why did you close the PR?

**Comment by jessehanson** [comment]
I'm sorry, I thought I needed to close the pull request and create a new one with the updated information but I 'll reopen this one since that isn't necessary. I haven't done a pull request before so I'm not used to the process.

**Comment by kwhitehall** [comment]
No problem! All about learning. So the process is to update the PR with the changes requested. This is done by updating your branch and then pushing It. If you are closing the PR you should indicate why.

**Comment by jessehanson** [comment]
When I made the correction I just changed the pdf file to a txt file, so locally I only see the text file and can't remove the pdf because I'm not seeing it. How again did you suggest I go about removing the pdf from the pull request? That's the only thing holding me up right now.

**Comment by kwhitehall** [comment]
@jessehanson, please git rm the pdf file.

**Pull request merged**
